"""prompt external source fields

Revision ID: 0e7849c272f7
Revises: aacdd5c588d7
Create Date: 2026-07-26 19:21:31.856167
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0e7849c272f7'
down_revision: str | None = 'aacdd5c588d7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', sa.String(length=1000), nullable=False))
        batch_op.add_column(sa.Column('source_url', sa.String(length=1000), nullable=False))
        batch_op.add_column(sa.Column('source_author', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_prompts_content_hash'), ['content_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompts_content_hash'))
        batch_op.drop_column('content_hash')
        batch_op.drop_column('source_author')
        batch_op.drop_column('source_url')
        batch_op.drop_column('cover_url')

    # ### end Alembic commands ###
