"""prompt favorites table

Revision ID: 7a645cc7cd51
Revises: 0e7849c272f7
Create Date: 2026-07-26 20:41:04.215294
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7a645cc7cd51'
down_revision: str | None = '0e7849c272f7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_favorites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('prompt_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'prompt_id', name='uq_user_prompt_favorite')
    )
    with op.batch_alter_table('prompt_favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_favorites_prompt_id'), ['prompt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_favorites_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_favorites_prompt_id'))

    op.drop_table('prompt_favorites')
    # ### end Alembic commands ###
