"""agents skills workflows tables

Revision ID: 82a0553bd654
Revises: c8f3a12d9e01
Create Date: 2026-07-29 17:26:18.074765
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '82a0553bd654'
down_revision: str | None = 'c8f3a12d9e01'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['agent_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['workflow_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('agent_type', sa.String(length=20), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('favorite_count', sa.Integer(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('cover_url', sa.String(length=1000), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_author', sa.String(length=200), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('tools', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['agent_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('skill_type', sa.String(length=20), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('favorite_count', sa.Integer(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('cover_url', sa.String(length=1000), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_author', sa.String(length=200), nullable=False),
    sa.Column('inputs_schema', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('graph', sa.Text(), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('workflow_type', sa.String(length=20), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('favorite_count', sa.Integer(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('cover_url', sa.String(length=1000), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_author', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['workflow_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_favorites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'agent_id', name='uq_user_agent_favorite')
    )
    with op.batch_alter_table('agent_favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_favorites_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('workflow_favorites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'workflow_id', name='uq_user_workflow_favorite')
    )
    with op.batch_alter_table('workflow_favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_favorites_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_favorites_workflow_id'), ['workflow_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_favorites_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_favorites_user_id'))

    op.drop_table('workflow_favorites')
    with op.batch_alter_table('agent_favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_favorites_agent_id'))

    op.drop_table('agent_favorites')
    op.drop_table('workflows')
    op.drop_table('skills')
    op.drop_table('agents')
    op.drop_table('workflow_categories')
    op.drop_table('agent_categories')
    # ### end Alembic commands ###
